### ISSUE TITLE
Weird behavior when no space between '//' and comment text

### ISSUE THREAD

**Issue by ironyman** [ssigwart/vscode-reflow#1]
First of all thank you for making this extension, I reformatting comments is really helpful for me since I write a lot of comments.

I noticed that if I select line 2 in the following listing and press C-q
```
1 // test
2 //test
3 // test
```
becomes
```
1 // test
2 // est
3 // test
```

and I select all three lines it would become
```
// test //test test
```

**Comment by ssigwart** [comment]
Thanks, @ironyman.  This should be fixed in version 1.0.2, which should be available within the hour.
